[network]
rpc_bind = "0.0.0.0:28443"
block_time = 30000
miner_address = "n3GRiDLKWuKLCw1DZmV75W1mE35qmW2tQm"
faucet_address = "n3GRiDLKWuKLCw1DZmV75W1mE35qmW2tQm"
bitcoind_rpc_host = "127.0.0.1:18443"
bitcoind_rpc_user = "devnet"
bitcoind_rpc_pass = "devnet"
genesis_timestamp = 1590765126
whitelisted_rpc_calls = [
  "listunspent",
  "importaddress",
  "sendrawtransaction",
  "getrawtransaction",
  "scantxoutset",
  "getrawmempool",
  "getblockhash",
]

[[blocks]]
count = 1
block_time = 10000
ignore_txs = false

[[blocks]]
count = 3
block_time = 20000
ignore_txs = false

[[blocks]]
count = 2
block_time = 1000
ignore_txs = true

[[blocks]]
count = 3
block_time = 20000
ignore_txs = true

[[blocks]]
count = 2
block_time = 1000
ignore_txs = true

[[blocks]]
count = 3
block_time = 20000
ignore_txs = false

[[blocks]]
count = 2
block_time = 1000
ignore_txs = true

[[blocks]]
count = 3
block_time = 20000
ignore_txs = false

[[blocks]]
count = 2
block_time = 1000
ignore_txs = true

[[blocks]]
count = 3
block_time = 20000
ignore_txs = false

[[blocks]]
count = 2
block_time = 1000
ignore_txs = true


# Faucet:
# Private Key          cTYqAVPS7uJTAcxyzkXWjmRGoCjkPcb38wZVRjyXov1RiRDWPQj3
# Public Key           02327e09dc18fee1d51fe2b19b487e01eba4e6adcb325bf102213fce7bbdcde6bd
# Address              n3k15aVS4rEWhVYn4YfAFjD8Em5mmsducg
# Format               p2pkh
# Network              testnet
# Compressed           true
