
# message_private_key = "2ZCxUV9BAKJrGnTPaamKHb4HVgj9ArQgEhowuTe7uRt3"
# message_private_key = "9e4d3b3ed869f0a133b992836615e53a515b225aba5109e10f41e556a8f96a5501"
message_private_key = "BewimTacGP8gtWgXTLLpLSqvck2T3RiNHG9AWcHbPB5v"
stacks_private_key = "69be0e68947fa7128702761151dc8d9b39ee1401e547781bb2ec3e5b4eb1b36f01"
node_host = "127.0.0.1:20443"
# node_host = "localhost:11111"
endpoint = "127.0.0.1:30000"
network = "testnet"
stackerdb_contract_id = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.signers-stackerdb"
signer_id = 0
signers = [
  { public_key = "swBaKxfzs4pQne7spxhrkF6AtB34WEcreAkJ8mPcqx3t", key_ids = [
    1,
    2,
    3,
    4,
  ] },
  { public_key = "yDJhntuJczbss1XGDmyWtG9Wpw5NDqoBBnedxmyhKiFN", key_ids = [
    5,
    6,
    7,
    8,
  ] },
  { public_key = "xNVCph6zd7HLLJcuwrWz1gNbFoPHjXxn7cyRvvTYhP3U", key_ids = [
    9,
    10,
    11,
    12,
  ] },
  { public_key = "p2wFfLEbwGCmxCR5eGa46Ct6i3BVjFrvBixRn7FnCQjA", key_ids = [
    13,
    14,
    15,
    16,
  ] },
  { public_key = "26jpUNnJPvzDJRJg3hfBn5s5MR4eQ4LLTokjrSDzByh4i", key_ids = [
    17,
    18,
    19,
    20,
  ] },
]
