
message_private_key = "B7HXWR7GK4E6n6239M86ycYh13AxoXxMU2DqowcQf2p9"
stacks_private_key = "7287ba251d44a4d3fd9276c88ce34c5c52a038955511cccaf77e61068649c178"
node_host = "127.0.0.1:20443"
endpoint = "localhost:30000"
network = "testnet"
# stackerdb_contract_id = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.signers-stackerdb"
# signer_id = 0
# signers = [
#             {public_key = "rvecz1zvgPPut6taccsUq5VTdSoX6kPbC5pa3MzUhBsY", key_ids = [1, 2]}
#         ]
